@startuml

actor Player
participant Game
participant Battle
participant UI
actor Enemy
activate Player
activate Game
activate Battle
Game -> Battle : run()
loop while Player.isAlive() && Enemy.isAlive()
    Battle -> Player : chooseAbility()
    Player -> Player : showUserMenu()
    Player -> Battle : p1Ability
    
    Battle -> Enemy : chooseAbility()
    Enemy -> Enemy : chooseAIAction()
    Enemy -> Battle : p2Ability
    Battle -> Player : applyDamage()
    Battle -> Enemy : applyDamage()
end
@enduml


