@startuml
participant Battle order 4
participant BattleLogic order 5
participant Playerturn order 6
participant Turn order 7
activate Battle
Battle -> BattleLogic : startBattle()
activate BattleLogic
loop
Battle -> BattleLogic : battleSequence
Playerturn -> Playerturn : getCurrAction(input String)
Playerturn -> Turn : setHasSurrenderred(boolean)
BattleLogic -> Turn : checkBattleEnd(turn)
Turn -> BattleLogic
end
BattleLogic -> BattleLogic : setHasWon(false)
BattleLogic -> BattleLogic : setHasBattleEnded(true)
BattleLogic -> Battle : setHasWon(boolean)
@enduml
