@startuml

actor Player
participant Game
participant Battle
participant Loot
participant LootUI
activate Player
activate Game
activate Battle
activate Loot
activate LootUI
Game -> Battle : run()
Battle -> Battle : startGameLoop()
Battle -> Game : hasWonCurrBattle()
deactivate Battle
Game -> Loot : setHasWon(boolean)
Game -> Loot : run()
alt Player wins the battle
    Loot -> Player : addGold()
    Loot -> LootUI : printLoot(loot)
else Player loses
    Loot -> LootUI : printNoLoot()
end
deactivate Loot
@enduml
