@startuml
package Functionalities {
    class Storage {
        - static final String FILE_DIRECTORY
        - static final String FILE_NAME
        - static final String LOAD_DELIMITER
        - static final String SAVE_DELIMITER
        + static void saveGame(Player, Event, Queue<Event>) throws RolladieException
        - static Character parseCharacterFromText(String, String[]) throws RolladieException
        - static Event parseEventFromText(Player, String[]) throws RolladieException
        + static Game loadGame() throws RolladieException
    }
}

package Game.Characters {
    class Character {
        + int[] healthBars
        + int attackValue
        + int defenseValue
        + String characterName
        + int maxHealth
        + toText(): String
    }
    class Player extends Character
    class Enemy extends Character
}

package Game.Events {
    class Event {
        + toText(): String
    }
    class Battle extends Event {
        + Battle(Player, Enemy)
    }
}

package Exceptions {
    class RolladieException extends Exception
}

package Game {
    class Game {
        + Game(Player, Event, Queue<Event>)
    }
}

Storage -> RolladieException : throws
Storage -> Player
Storage -> Enemy
Storage -> Event
Storage -> Battle
Storage -> Game

@enduml
